- name: Cleanup everything !!
  hosts: localhost
  connection: local
  vars_files:
    - ./variables.yml
  tasks:
    - name: Deleting resource group - '{{ resource_group }}'
      azure_rm_resourcegroup:
        name: '{{ resource_group }}'
        force_delete_nonempty: yes
        state: absent
      register: rg
    - debug:
        var: rg