- name: Create Azure VM
  hosts: localhost
  connection: local
  vars_files:
    - ./variables.yml
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: '{{ resource_group }}'
        location: '{{ location }}'
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: '{{ resource_group }}'
        name: '{{ vnetName }}'
        address_prefixes: '{{ ipAddr }}'
    - name: Add subnet
      azure_rm_subnet:
        resource_group: '{{ resource_group }}'
        name: '{{ subNetName }}'
        address_prefix: '{{ ipSubNet }}'
        virtual_network: '{{ vnetName }}'
    - name: Create Network Security Group with allowed ports
      azure_rm_securitygroup:
        resource_group: '{{ resource_group }}'
        name: '{{ nsgName }}'
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: Extra Port for Development
            destination_port_range: '{{ appPort }}'
            access: Allow
            priority: 1002
            direction: Inbound
    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: '{{ resource_group }}'
        name: '{{ nicName }}'
        virtual_network: '{{ vnetName }}'
        subnet: '{{ subNetName }}'
        public_ip_name: '{{ pubIpName }}'
        security_group: '{{ nsgName }}'
    - name: Create SSH key for connection
      openssh_keypair:
        path: "./{{ sshKeyName }}"
        type: rsa
        size: 4096
        state: present
        force: no
    - name: Cat the public key into a variable
      command:
        chdir: ./
        cmd: cat "{{ sshKeyName }}.pub"
      register: cat_contents
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: '{{ resource_group }}'
        name: '{{ vmName }}'
        vm_size: Standard_DS1_v2
        admin_username: '{{ vmUserName }}'
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/{{ vmUserName }}/.ssh/authorized_keys
            key_data: "{{ cat_contents.stdout }}"
        network_interfaces: '{{ nicName }}'
        image:
          offer: debian-10
          publisher: Debian
          sku: '10'
          version: latest
        state: present
    - name: Get details for Public IP
      azure_rm_publicipaddress_info:
        resource_group: '{{ resource_group }}'
        name: '{{ pubIpName }}'
      register: cardDetails
    - name: Delete inventory file
      file:
        path: ./inventory.yml
        state: absent
    - name: Create new inventory file
      file:
        path: "./inventory.yml"
        state: touch
    - name: Update inventory details
      lineinfile: 
        line: "{{ vmName }} ansible_host={{ cardDetails['publicipaddresses'][0]['ip_address'] }} ansible_user={{ vmUserName }} ansible_ssh_private_key_file=./{{ sshKeyName }}"
        path: ./inventory.yml
    - name: Delete login file
      file:
        path: ./login.sh
        state: absent
    - name: Create ligin file
      file:
        path: "./login.sh"
        state: touch
    - name: Update login details
      lineinfile: 
        line: "ssh -o StrictHostKeyChecking=no {{ vmUserName }}@{{ cardDetails['publicipaddresses'][0]['ip_address'] }} -i ./{{ sshKeyName }}"
        path: ./login.sh
    - name: Make script executable
      command:
        chdir: ./
        cmd: chmod +x ./login.sh