- name: Setup docker server and build docker files.
  hosts: ansibleVM
  remote_user: azureuser
  become: yes
  vars_files:
    - ./variables.yml
  tasks:
    - name: Install Python3 APT
      apt: 
        name: ['python3-apt']
        state: latest
    - name: Gather all installed packages
      package_facts:
        manager: apt
    - name: Downlaod Docker Script and install (only if its not installed already)
      command:
        cmd: '{{ item }}'
      with_items: 
        - curl -fsSL https://get.docker.com -o '{{ dockerInstallFile }}'
        - chmod +x ./{{ dockerInstallFile }}
        - ./{{ dockerInstallFile }}
      when: '"docker-ce" not in ansible_facts.packages'
    - name: Create directory for docker
      file:
        path: '{{ dockerHome }}'
        state: directory
    - name: Copy docker file and compose from local to remote
      copy:
        src: '{{ localDocker }}'
        dest: '{{ dockerHome }}'
    - name: Run docker build command
      command:
        chdir: '{{ dockerHome }}'
        cmd: docker build -t '{{ dockerUser }}'/'{{ appName }}' .
    - name: Start Server
      command:
        chdir: '{{ dockerHome }}'
        cmd: docker run -d -p '{{ appPort }}:{{ nginxPort }}' '{{ dockerUser }}'/'{{ appName }}'
       