- name: Setup docker server and build docker files.
  hosts: ansibleVM
  remote_user: azureuser
  become: yes
  vars_files:
    - ./variables.yml
  tasks:
    - name: Install Python3 APT
      apt: 
        name: ['python3-apt']
        state: latest
    - name: Gather all installed packages
      package_facts:
        manager: apt
    - name: Downlaod Docker Script and install (only if its not installed already)
      command:
        cmd: '{{ item }}'
      with_items: 
        - curl -fsSL https://get.docker.com -o '{{ dockerInstallFile }}'
        - chmod +x ./{{ dockerInstallFile }}
        - ./{{ dockerInstallFile }}
      when: '"docker-ce" not in ansible_facts.packages'
    - name: Create local directory for docker
      file:
        path: '{{ dockerHome }}'
        state: directory
    - name: Copy docker file and compose from local to remote
      copy:
        src: '{{ localDocker }}'
        dest: '{{ dockerHome }}'
    - name: Build Image
      command:
        chdir: '{{ dockerHome }}'
        cmd: docker build -t '{{ dockerUser }}/{{ appName }}' .
    - name: Archive image
      command:
        chdir: '{{ dockerHome }}'
        cmd: docker save -o {{ imageArchive }} {{ dockerUser }}/{{ appName }} 
    - name: Downlaod docker archive image from remote to local
      fetch:
        src: '{{ dockerHome }}/{{ imageArchive }}'
        dest: '{{ localDocker }}'
        flat: yes
       